### PR TITLE
Fix getting properties

### LINKED ISSUE #22: `get_block_dev_properties` doesn't work
I've found one another bug in [my last PR.](https://github.com/cholcombe973/block-utils/pull/19)

```rust
pub fn get_block_dev_properties(
    device_path: impl AsRef<Path>,
) -> BlockResult<HashMap<String, String>> {
    let syspath = device_path
        .as_ref()
        .file_name()
        .map(PathBuf::from)
        .ok_or_else(|| {
            BlockUtilsError::new(format!(
                "Unable to get file_name on device {:?}",
                device_path.as_ref()
            ))
        })?;

    let udev_device = udev::Device::from_syspath(&syspath)?; //HERE
    Ok(udev_device
        .clone()
        .properties()
        .map(|property| {
            let key = property.name().to_string_lossy().to_string();
            let value = property.value().to_string_lossy().to_string();
            (key, value)
        })
        .collect()) // We can't return iterator because `udev_device` doesn't live long enough
}
```

`udev::Device::from_syspath` expects full syspath like `/sys/block/loop0` instead of just a sysname `loop0` like in `udevadm` CLI.
`udevadm` CLI expects sysname and found exact syspath automatically. 
So, these functions `get_block_dev_properties` and `get_block_dev_property` doesn't work properly.

And I'm not sure how to fix it right now. As far as I understand, this path can lay not only in `/sys/block/$dev` but also in other `/sys/` subdirectories.

Unfortunately I don't have enough time right now so I'm going to investigate it over the next few weeks.

### PR DESCRIPTION
**Pull request by Apostoln**
- Use syspath instead of sysname for udev
 - Add dev_path_to_sys_path() function
 - Return error if there no sys path

Close #22 

There was a bug with incorrect `syspath` for `udev`. I've fixed it making an assumption we work only with block devices (and return the `Error` otherwise) and the `syspath` is always like `/sys/class/block/`. 

I've tested it locally and with the integration tests in our project where we use `block-utils`. However, it's a bit complicated to write unit tests in the scope of this repo because it requires a kind of testing framework for loop devices, disks, partitions, filesystems, and so on. We have a kind of such one in progress, but it hasn't opensourced yet.

Well, I'm not sure by 100% that the assumption about `/sys/class/block` is general truth and this path exists for all block devices. There are a lot of other sys paths like `/sys/devices/virtual/block/` and  `/sys/block/`. Anyway, it looks like `/sys/class/block` is an expected `syspath`  according to the examples in `udev`.

### CODE REVIEW

**Comment by Apostoln** [comment]
I've found some potential problems, please don't merge now.

**Comment by Apostoln** [comment]
Doesn't matter, it were unrelated problems with Fedora 33.

**Comment by cholcombe973** [comment]
This PR looks reasonable to me. Would you like me to merge it?

**Comment by Apostoln** [comment]
@cholcombe973 Yes, thank you :)

**Pull request merged**
